# Generated by Django 5.1.3 on 2024-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_flight_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
